CREATE TABLE Airlines (
  	AIRLINE_ID char(10)  NOT NULL PRIMARY KEY,
	AIRLINE_NAME char(256)
);


CREATE TABLE Airports (
  	AIRPORT_ID char(10) NOT NULL PRIMARY KEY,
	AIRPORT_NAME char(256) NOT NULL
);


CREATE TABLE Flight_Airline (
  	FLIGHT_ID char(10) NOT NULL PRIMARY KEY,
	AIRLINE char(10) NOT NULL,
	CONSTRAINT FK_Airline FOREIGN KEY (AIRLINE) 
		REFERENCES Airlines(AIRLINE_ID)
);


CREATE TABLE Flight_Route (
  	FLIGHT_ID char(10) NOT NULL PRIMARY KEY,
	ORIGIN_AIRPORT char(10) NOT NULL,
	DESTINATION_AIRPORT char(10) NOT NULL,
	CONSTRAINT FK_OriginAirport FOREIGN KEY (ORIGIN_AIRPORT) 
		REFERENCES Airports(AIRPORT_ID),
	CONSTRAINT FK_DestinationAirport FOREIGN KEY (DESTINATION_AIRPORT) 
		REFERENCES Airports(AIRPORT_ID),
	CONSTRAINT FK_RouteAirline FOREIGN KEY (FLIGHT_ID) 
		REFERENCES Flight_Airline(FLIGHT_ID)
);

